### ISSUE TITLE
ES6 Support

### ISSUE THREAD

**Issue by Xe** [jwatte/jsframework#2]
Hello,

I am looking over using this wonderful project for my MVP CEO EIASD demo for creation of my dynamic scalable infrastructure. However this is almost suitable for my needs.

You forgot to add ECMAScript 6 Support. I am sure you would benefit greatly from promises and future-passings.

With thanks,

KINDLY INVESTOR

**Comment by jwatte** [comment]
Hey, thanks for the comments! That's actually something we've considered internally, and have open on an internal issue tracker. I will close your issue here as resolved in the meanwhile. Thanks again!
